### ISSUE TITLE
Hope to support third-party API access and access methods, such as news, stocks, and Wikipedia

### ISSUE THREAD

**Issue by vtayh** [FlamingoFiesta/Chatgpt_telegram_bot#1]
ERROR: for chatgpt_telegram_bot  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'

**Comment by FlamingoFiesta** [comment]
@vtayh  

I see you changed the title of the initial issue, have you been able to solve it? If not, please give me more information as to the context in which the error occurred and I will look into it.

As for the third-party API methods, I am planning on integrating some. First I want to add the capability to extract the text from files. After, I will look again into some free API's which could be useful to integrate. Any API's that cost money will need to be very useful for the integration to be worth it.

I am open to any suggestions for the API's.

**Comment by vtayh** [comment]
Thank you for your response. I have already solved the previous problem,
and now it runs very well. However, it lacks a bit of fun, such as
real-time news, stock information, cryptocurrency information, financial
news, and other popular features. If these functions are implemented, you
can surpass Karfly.

FlamingoFiesta ***@***.***> 于 2024年6月7日周五 23:16写道：
